# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm audit        # Run npm audit to identify and show vulnerabilities
    npm audit fix    # Attempt to automatically fix vulnerabilities
    npm run build    # Run your build script
  displayName: 'npm install, audit, and build'

